pimpmyprose/pimpmyprose/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Imports for Django Rest Framework
from rest_framework import routers
from prose import views

# Register routers for Prose and Pimp views
router = routers.DefaultRouter()
router.register( r'prose', views.ProseViewSet, base_name = 'prose' )
router.register( r'pimp', views.PimpViewSet, base_name = 'pimp' )

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pimpmyprose.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

	url( r'^', include( 'prose.urls', namespace = "prose" ) ),
    url( r'^admin/', include(admin.site.urls) ),

	# Urls for Django Rest Framework
	url( r'^api/', include( router.urls ) ),
	url( r'^api-auth/', include( 'rest_framework.urls', namespace = 'rest_framework' ) ),
)

# Include urls for static files. Offline deployment
# Only works of DEBUG is True
urlpatterns += staticfiles_urlpatterns()

pimpmyprose/prose/urls.py
from django.conf.urls import patterns, url, include

from prose import views


urlpatterns = patterns( '',
	# ex: /prose/
	url( r'^$', views.index, name = 'index' ),

	# angularJS version of detail
	# ex: /prose_angular/5/
	url( r'^(?P<prose_id>\d+)/$', views.detail, name = 'detail' ),

	# ex: /prose/pimp/10/upvote/
	url( r'^upvote/$', views.upvote, name = 'upvote' ),

	# ex: /prose/pimp/10/downvote/
	url( r'^downvote/$', views.downvote, name = 'downvote' ),

	# ex: /prose/register/
	url( r'^register/$', views.register, name = 'register' ),

	# ex: /prose/login/
	url( r'^login/$', views.user_login, name = 'login' ),

	# ex: /prose/logout/
	url( r'^logout/$', views.user_logout, name = 'logout' ),

	# ex: /prose/profile/1/
	url( r'^profile/(?P<user_id>\d+)/$', views.profile, name = 'profile' ),

	# ex: /prose/profile/manage/
	url( r'^profile/manage/$', views.profile_manage, name = 'profile_manage' ),

	# Users a certain user is following
	# ex: /prose/profile/1/following
	url( r'^profile/(?P<user_id>\d+)/following/$', views.following, name = 'following' ),

	# Pimps from all users a user is following
	# ex: /prose/profile/1/following/pimps
	url( r'^profile/(?P<user_id>\d+)/following/pimps/$', views.following_pimps, name = 'following_pimps' ),

	# Prose from all users a user is following
	# ex: /prose/profile/1/following/prose
	url( r'^profile/(?P<user_id>\d+)/following/prose/$', views.following_prose, name = 'following_prose' ),

	# Users who are following a certain user
	# ex: /prose/profile/1/followers
	url( r'^profile/(?P<user_id>\d+)/followers/$', views.followers, name = 'followers' ),

	# ex: /prose/notifications/
	url( r'^notifications/$', views.notifications, name = 'notifications' ),

	# ex: /prose/follow/
	url( r'^follow/$', views.followToggle, name = 'follow' ),

	# ex: /prose/search
	url( r'^search/$', include( 'haystack.urls' ) ),
)

pimpmyprose/prose/forms.py
from prose.models import UserProfile, Prose, Pimp
from django.contrib.auth.models import User
from django import forms

class UserForm( forms.ModelForm ):
	username = forms.CharField( widget = forms.TextInput( attrs = { 'class' : 'form-control form-control-custom' } ) )
	email = forms.EmailField( widget = forms.TextInput( attrs = { 'class' : 'form-control form-control-custom' } ) )
	password = forms.CharField( widget = forms.PasswordInput( attrs = { 'class' : 'form-control form-control-custom' } ) )
	passwordValidate = forms.CharField( label = 'Validate Password', widget = forms.PasswordInput( attrs = { 'class' : 'form-control form-control-custom' } ) )

	class Meta:
		model = User
		fields = ( 'username', 'email', 'password' )

	def clean_username(self):
		username = self.cleaned_data['username']
		if User.objects.filter( username = username ).exists():
			raise forms.ValidationError( "Username already exists." )
		return username

	def clean_email(self):
		email = self.cleaned_data['email']
		if User.objects.filter( email = email ).exists():
			raise forms.ValidationError( "Email already exists." )
		return email

	def clean(self):
		form_data = self.cleaned_data
		if not 'password' in form_data or not 'passwordValidate' in form_data:
			self._errors['password'] = ['Password fields cannot be empty']
			return form_data

		if form_data['password'] != form_data['passwordValidate']:
			self._errors['password'] = ['Password fields do not match.']
			return form_data

# This will have more fields later
class UserProfileForm( forms.ModelForm ):
	class Meta:
		model = UserProfile
		fields = ();

# Form to edit user account, does not include username
class UserManageForm( forms.Form ):
	email = forms.EmailField( widget = forms.TextInput( attrs = { 'class' : 'form-control form-control-custom' } ) )
	password = forms.CharField( widget = forms.PasswordInput( attrs = { 'class' : 'form-control form-control-custom' } ) )
	passwordValidate = forms.CharField( label = 'Validate Password', widget = forms.PasswordInput( attrs = { 'class' : 'form-control form-control-custom' } ) )

	def __init__( self, *args, **kwargs ):
		self.user = kwargs.pop( 'user', None )
		super( UserManageForm, self ).__init__( *args, **kwargs )

	def clean_email(self):
		email = self.cleaned_data['email']
		# User can keep their email
		if email == self.user.email:
			return email

		# Cant use an existing email
		if User.objects.filter( email = email ).exists():
			raise forms.ValidationError( "Email already exists." )
		return email

	def clean(self):
		form_data = self.cleaned_data
		if not 'password' in form_data or not 'passwordValidate' in form_data:
			self._errors['password'] = ['Password fields cannot be empty']
			return form_data

		if form_data['password'] != form_data['passwordValidate']:
			self._errors['password'] = ['Password fields do not match.']
			return form_data

# Form for submitting a prose
class ProseForm( forms.ModelForm ):
	prose_text = forms.CharField( widget = forms.Textarea( attrs = { 'class' : 'pimpProseSubmit', 'onkeyup' : 'getRemainingCharacters(this)' } ), label = '', max_length = 250 )

	class Meta:
		model = Prose
		fields = ( 'prose_text', )

	def clean_prose_text(self):
		prose_text = self.cleaned_data['prose_text']
		if Prose.objects.filter( prose_text = prose_text ).exists():
			raise forms.ValidationError( "Prose Text already exist." )
		return prose_text

# Form for submitting a pimp
class PimpForm( forms.ModelForm ):
	pimp_text = forms.CharField( widget = forms.Textarea( attrs = { 'class' : 'pimpProseSubmit', 'onkeyup' : 'getRemainingCharacters(this)' } ), label= '', max_length = 250 )

	class Meta:
		model = Pimp
		fields = ( 'pimp_text', )

	def clean_pimp_text(self):
		pimp_text = self.cleaned_data['pimp_text']
		if Pimp.objects.filter( pimp_text = pimp_text ).exists():
			raise forms.ValidationError( "Pimp Text already exist." )
		return pimp_text

pimpmyprose/prose/views.py
import datetime
from itertools import chain

from django.shortcuts import get_object_or_404, render, render_to_response

from django.template import RequestContext

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.forms.util import ErrorList
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone

from prose.models import Prose, Pimp, UserProfile
from prose.forms import UserForm, UserProfileForm, UserManageForm, ProseForm, PimpForm

# Include custom functions for hot ranking (from reddit)
from ranking_functions import getHotScore

# Rest Framework
from rest_framework import viewsets, permissions
from serializers import ProseSerializer, PimpSerializer
from permissions import IsOwnerOrReadOnly

def register(request):
	context = RequestContext(request)

	if ( request.user.is_authenticated() ):
		return render_to_response(
				'prose/register.html',
				{},
				context )

	registered = False

	if request.method == 'POST':
		user_form = UserForm( data = request.POST )
		profile_form = UserProfileForm( data = request.POST )

		if user_form.is_valid() and profile_form.is_valid:
			# Save user data from form into user
			user = user_form.save()

			# Hash password and save user again
			user.set_password( user.password )
			user.save()

			profile = profile_form.save( commit = False )
			profile.user = user

			profile.save()

			registered = True

			# Log user in
			userLogin = authenticate( username = request.POST['username'], password = request.POST['password'] )
			login( request, userLogin)

		else:
			print user_form.errors, profile_form.errors

	else:
		user_form = UserForm()
		profile_form = UserProfileForm()

	return render_to_response(
			'prose/register.html',
			{ 'user_form' : user_form, 'profile_form' : profile_form, 'registered' : registered },
			context )

def user_login(request):
	context = RequestContext(request)

	# No need to do anything else if user is already authenticated
	# Maybe just redirect to index
	if ( request.user.is_authenticated() ):
		return render_to_response( 'prose/login.html', {}, context )

	if request.method == 'POST':

		username = request.POST['username']
		password = request.POST['password']

		user = authenticate( username = username, password = password )

		if user:
			if user.is_active:
				login( request, user )
				return HttpResponseRedirect( reverse( 'prose:index' ) )
			else:
				return HttpResponseRedirect( "Your pimpMyProse account is disabled." )
		else:
			print "Invalid login detail: {0}, {1}".format( username, password )
			return render_to_response( 'prose/login.html', { 'invalidLogin' : True }, context )

	else:
		return render_to_response( 'prose/login.html', {}, context )

@login_required
def user_logout(request):
	logout(request)

	return HttpResponseRedirect( reverse( 'prose:index' ) )

# Main page, where new prose can be posted
def index( request ):
	context = RequestContext(request)

	# Allow user to post Prose from index
	if request.user.is_authenticated() and request.method == 'POST':
		prose_form = ProseForm( data = request.POST )

		if prose_form.is_valid():
			# Save prose data from form into prose
			prose = prose_form.save( commit = False )
			# Reset prose form so no data on page reload
			prose_form = ProseForm()

			prose.user = request.user
			prose.pub_date = timezone.now()

			prose.save()

			# Redirect to the detail for this newly created Prose
			return HttpResponseRedirect( reverse( 'prose:detail', args = [ prose.id ] ) )

		else:
			print prose_form.errors

	else:
		prose_form = ProseForm()

	return render_to_response(
			'prose/index.html',
			{ 'prose_form' : prose_form },
			context )

# View to show all users another user is following
def following( request, user_id ):
	context = RequestContext(request)

	# Get the user profile to see who they are following
	user = get_object_or_404( User, pk = user_id )
	userProfile = user.userProfile

	# From this userProfile, get all users they are following
	following = userProfile.follows.all()

	# Pass users that are followed to the view
	return render_to_response(
			'prose/follows.html',
			{ 'userProfile' : userProfile, 'following' : following },
			context )

# Pimps from all users another user is following
def following_pimps( request, user_id ):
	context = RequestContext(request)

	# Get user profile to see who they are following
	user = get_object_or_404( User, pk = user_id )
	userProfile = user.userProfile

	return render_to_response(
			'prose/follows_pimps.html',
			{ 'userProfile' : userProfile },
			context )

# Pimps from all users another user is following
def following_prose( request, user_id ):
	context = RequestContext(request)

	# Get user profile to see who they are following
	user = get_object_or_404( User, pk = user_id )
	userProfile = user.userProfile

	return render_to_response(
			'prose/follows_prose.html',
			{ 'userProfile' : userProfile },
			context )

# View to show all users following a user
def followers( request, user_id ):
	context = RequestContext(request)

	# Get user profile to see their followers
	user = get_object_or_404( User, pk = user_id )
	userProfile = user.userProfile

	# From this userProfile, get all their followers
	followers = userProfile.followed_by.all()

	# Pass user's followers to the view
	return render_to_response(
			'prose/followers.html',
			{ 'userProfile' : userProfile, 'followers' : followers },
			context )

def detail( request, prose_id ):
	context = RequestContext(request)

	prose = get_object_or_404( Prose, pk = prose_id )

	if request.user.is_authenticated() and request.method == 'POST':
		pimp_form = PimpForm( data = request.POST )

		if pimp_form.is_valid():
			# Check to see if pimp already exists for this prose
			pimp_text = pimp_form.cleaned_data['pimp_text']
			if prose.pimpExists( pimp_text ):
				# If pimp already exists, return normal PimpForm and error
				pimp_form = PimpForm()
				pimp_form.errors["pimp_text"] = ErrorList( [u"Pimp already exists."] )

			# Pimp does not exist, create and save
			else:
				# Save prose data from form into prose
				pimp = pimp_form.save( commit = False )
				# Reset pimp form for page reload, no repost
				pimp_form = PimpForm()

				pimp.user = request.user
				pimp.pub_date = timezone.now()
				pimp.prose = prose

				# Must save before m2m value can be added
				pimp.save()

				# Set current user to be an upvoter
				pimp.upvotes.add( request.user )

				# Final save
				pimp.save()

				# Also, notify the prose user that someone pimped his prose
				prose.user.userProfile.pimpNotifications.add(pimp)
				prose.save()

		else:
			print pimp_form.errors

	else:
		pimp_form = PimpForm()

	return render_to_response(
			'prose/detail.html',
			{ 'pimp_form' : pimp_form, 'prose' : prose },
			context )

@login_required
def upvote(request):
	context = RequestContext(request)
	pimp_id = None
	if request.method == 'POST':
		pimp_id = request.POST.get( 'pimp_id' )

	pimp = get_object_or_404( Pimp, pk = pimp_id )

	pimp.downvotes.remove( request.user )
	if pimp.upvotes.filter( pk = request.user.id ):
		pimp.upvotes.remove( request.user )
	else:
		pimp.upvotes.add( request.user )

	pimp.save()

	# Return the new score to be redisplayed
	return HttpResponse( pimp.score )

@login_required
def downvote( request ):
	context = RequestContext(request)
	pimp_id = None
	if request.method == 'POST':
		pimp_id = request.POST.get('pimp_id')

	pimp = get_object_or_404( Pimp, pk = pimp_id )

	pimp.upvotes.remove( request.user )
	if pimp.downvotes.filter( pk = request.user.id ):
		pimp.downvotes.remove( request.user )
	else:
		pimp.downvotes.add( request.user )

	pimp.save()

	# Return the new score to be redisplayed
	return HttpResponse( pimp.score )

# View a use profile, including self
def profile( request, user_id ):
	context = RequestContext(request)

	user = get_object_or_404( User, pk = user_id )
	userProfile = user.userProfile

	# Only show follow status if logged in
	followingUser = "Null"
	if request.user.is_authenticated():
		if request.user.userProfile.isFollowingUser( user ):
			followingUser = "Followed"
		else:
			followingUser = "Not Followed"

	return render_to_response(
			'prose/profile.html',
			{	'userProfile' : userProfile, 'followingUser' : followingUser },
			context )

# View current user's notifications
@login_required
def notifications(request):
	context = RequestContext(request)

	# Show notifications
	pimp_notification_list = request.user.userProfile.getClearPimpNotifications()

	# Get all user pimp responses
	pimp_response_list = request.user.userProfile.getPimpResponses()

	# Subtract notification list from the overall pimp_response_list
	pimp_response_list = [ pimp for pimp in pimp_response_list if pimp not in pimp_notification_list ]

	# Pass variable to indicate that Pimp's should link to their parent Prose
	show_parent_prose = True

	return render_to_response(
			'prose/notifications.html',
			{ 'pimp_notification_list' : pimp_notification_list, 'pimp_response_list' : pimp_response_list, 'show_parent_prose' : show_parent_prose },
			context )

# Manage the user profile
@login_required
def profile_manage( request ):
	context = RequestContext(request)

	if request.method == 'POST':
		# Edited Form to allow passing in request, to allow user to keep email
		userManage_form = UserManageForm( data = request.POST, user = request.user )

		if userManage_form.is_valid():
			currUser = User.objects.get( pk = request.user.id )

			# Save info from form into user
			currUser.email = request.POST['email']

			if not request.POST['password'] == '':
				currUser.set_password( request.POST['password'] )

			currUser.save()

			# Log user in
			userLogin = authenticate( username = request.user.username, password = request.POST['password'] )

pimpmyprose/templates/prose/detail.html
{% extends "prose/base.html" %}
{% load staticfiles %}
{% block title %}pimpMyProse - Viewing a Prose{% endblock %}

{% block content %}

{% if user.is_authenticated and user != prose.user and not user.userProfile.getPimpsAmt %}
<div class="jumbotron">
	<h2>Help <a href="{% url 'prose:profile' prose.user.id %}">{{ prose.user.username }}</a> by Pimping your first Prose!</h2>
	<p>
		{{ prose.user.username }} is looking for help with their Prose, show what you have to offer!
	</p>
</div>

{% endif %}

<div class="pimpProseBox">
	<h3><a href="{% url 'prose:profile' prose.user.id %}">{{ prose.user.username }}</a></h3>
	<p>{{ prose.prose_text }}</p>
	<p></p>
</div>
<a href="//www.reddit.com/submit" onclick="window.location = '//www.reddit.com/submit?url=' + encodeURIComponent(window.location); return false"> <img src="//www.redditstatic.com/spreddit1.gif" alt="submit to reddit" border="0" /> </a>
<br>

{% if user.is_authenticated %}

	{% if prose.user != user %}
	<!-- Form to post a new Pimp -->
	<form id="pimp_form" method="post" action="{% url 'prose:detail' prose.id %}">
		{% csrf_token %}

		<div class="pimpProse_form_label">Pimp this Prose:</div>
		{{ pimp_form.as_p }}

		<button type="submit" class="btn btn-primary pimpProseSubmitBtn" name="submit">Pimp</button>
		<div id="remainingCharacters"></div>
	</form>
	{% endif %}

{% else %}
Must be logged in to pimp this prose!

{% endif %}

<br>

{% include "prose/pimp_list_angular.html" %}

{% endblock %}

{% block angularJS %}
<!-- Load angularJS, mainApp, and default django URLs -->
{% include "prose/angularJS.html" %}

<!-- For the detail page, get the id of the current prose and load as query parameter -->
<script>
	var pimpsQueryParameter = '?prose_id=' + {{ prose.id }};
	var hideParentLink = true;
</script>

<!-- Load the controller for the detail page -->
<script src="{% static 'js/angular/pimpsController.js' %}"></script>
{% endblock %}

pimpmyprose/templates/prose/followers.html
{% extends "prose/base.html" %}
{% block title %}pimpMyProse - {{ userProfile.user.username }}'s Followers{% endblock %}

{% block content %}
{% if followers %}
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><a href="{% url 'prose:profile' userProfile.user.id %}">{{ userProfile.user.username }}</a>'s Followers</h3>
  </div>
  {% for userProfile in followers %}
  <ul class="list-group">
    <li class="list-group-item"><a href="{% url 'prose:profile' userProfile.user.id %}">{{ userProfile.user.username }}</a></li>
  </ul>

  {% endfor %}
</div>

{% else %}
{{ userProfile.user.username }} has no followers.

{% endif %}

{% endblock %}

pimpmyprose/templates/prose/follows.html
{% extends "prose/base.html" %}
{% block title %}pimpMyProse - Users Followed by {{ userProfile.user.username }}{% endblock %}

{% block content %}
{% if following %}
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Users Followed by <a href="{% url 'prose:profile' userProfile.user.id %}">{{ userProfile.user.username }}</a></h3>
  </div>
  {% for userProfile in following %}
  <ul class="list-group">
    <li class="list-group-item"><a href="{% url 'prose:profile' userProfile.user.id %}">{{ userProfile.user.username }}</a></li>
  </ul>

  {% endfor %}
</div>

<a href="{% url 'prose:following_prose' user.id %}"><button class="btn btn-success"/>Followed Prose</button></a>
<a href="{% url 'prose:following_pimps' user.id %}"><button class="btn btn-success"/>Followed Pimps</button></a>

{% else %}
{{ userProfile.user.username }} is not following anyone.

{% endif %}

{% endblock %}

pimpmyprose/templates/prose/index.html
{% extends "prose/base.html" %}
{% load staticfiles %}
{% block title %}pimpMyProse{% endblock %}

{% block content %}

{% if user.is_authenticated %}

{% if not user.userProfile.getProsesAmt %}
<div class="jumbotron">
	<h2>Post your first Prose!</h2>
	<p>
		Say something, anything! People are here to help you say what you want to say, better!
	</p>
</div>

{% elif not user.userProfile.getPimpsAmt %}
<div class="jumbotron">
	<h2>Help someone by Pimping your first Prose!</h2>
	<p>
		A lot of people need help with their Prose, show what you have to offer!
	</p>
</div>

{% endif %}

<!-- Form to post a new Prose -->
<form id="prose_form" method="post" action="{% url 'prose:index' %}">
	{% csrf_token %}

	<div class="pimpProse_form_label">Post a new Prose:</div>
	{{ prose_form.as_p }}

	<button type="submit" class="btn btn-primary pimpProseSubmitBtn" name="submit" />Prose</button>
	<div id="remainingCharacters"></div>
</form>

<!-- Links for user to view Prose and Pimps from followed users -->
<br>
<a href="{% url 'prose:following_prose' user.id %}"><button class="btn btn-success"/>Followed Prose</button></a>
<a href="{% url 'prose:following_pimps' user.id %}"><button class="btn btn-success"/>Followed Pimps</button></a>

{% else %}
Must be logged in to prose!

{% endif %}

<br>

<h2>All new Prose:</h2>
{% include "prose/prose_list_angular.html" %}

{% endblock %}

{% block angularJS %}
<!-- Load angularJS, mainApp, and default django URLs -->
{% include "prose/angularJS.html" %}

<!-- For the profile_pimp page, get the id of the current user -->
<script>var proseQueryParameter = '';</script>

<!-- Load the controller for the profile_pimps page -->
<script src="{% static 'js/angular/proseController.js' %}"></script>
{% endblock %}

pimpmyprose/templates/prose/latest_prose_list.html
{% if latest_prose_list %}
<div class="table-responsive">
	<table class="table">
		<tr class="pimpProseTableHeader">
			<th><center>Full Score</center></th>
			<th>Prose</th>
			<th><center>User</center></th>
		</tr>
		{% for prose in latest_prose_list %}
		<tr class="pimpProseTableOtherRows">
			<th><center>{{ prose.pimpScoreSum }}</center></th>
			<th><a href="{% url 'prose:detail' prose.id %}">{{ prose.prose_text }}</a></th>
			<th><center><a href="{% url 'prose:profile' prose.user.id %}">{{ prose.user.username }}</a></center></th>
		</tr>
		{% endfor %}
	</table>
</div>

{% else %}
<p>There are no Prose.</p>
{% endif %}

pimpmyprose/templates/prose/login.html
{% extends "prose/base.html" %}
{% block title %}pimpMyProse - Login{% endblock %}

{% block content %}

<h1>Login to pimpMyProse</h1>

{% comment %}
The if invalidlogin should be replaced with a {% for message in message.errors %}

{% endcomment %}
{% if invalidLogin %}
pimpMyProse says: <strong>Invalid login details were supplied.</strong> Redirecting to login form in 5 seconds.

<br><br><a href="{% url 'prose:login' %}">Return to the login page.</a>

<script>
	redirect( "{% url 'prose:login' %}" );
</script>

{% elif user.is_authenticated %}
pimpMyProse says: <strong>You are already logged in!</strong>
<a href="{% url 'prose:index' %}">Return to the homepage.</a><br />

{% else %}
<form id="login_form" method="post" action="{% url 'prose:login' %}">
	{% csrf_token %}
	Username: <input type="text" name="username" value="" size="50" class="form-control form-control-custom" />
	<br />
	Password: <input type="password" name="password" value="" size="50" class="form-control form-control-custom" />
	<br />
	
	<button type="submit" class="btn btn-primary" name="submit" />Submit</button>

</form>

{% endif %}

{% endblock %}

pimpmyprose/templates/prose/navBar.html
{% load staticfiles %}
<nav class="navbar navbar-inverse navbar-fixed-top navbar-custom">
	<div class="col-md-2"></div>
	<div class="container-fluid col-md-8">
		<div class="navbar-header">
			<a class="navbar-brand" href="{% url 'prose:index' %}">
				<img src="{% static 'images/navLogo.png' %}" alt="pimpMyProse">
			</a>
		</div>

		<form class="navbar-form navbar-left" role="search" action="{% url 'prose:haystack_search' %}">
			<div class="form-group">
				<input name="q" type="text" class="form-control" placeholder="Search Proses">
			</div>
			<button type="submit" class="btn btn-sm btn-primary">Go</button>
		</form>

		<ul class="nav navbar-nav navbar-right">

			{% if user.is_authenticated %}
			<li><a href="{% url 'prose:logout' %}"><button type="button" class="btn btn-sm btn-primary">Logout</button></a></li>
			<li><a class="notifications-icon" href="{% url 'prose:notifications' %}"><p class="navbar-text"><span class="glyphicon glyphicon-comment {% if user.userProfile.hasNotifications %}unread{% endif %}"></span> ({{ user.userProfile.getNotificationsCount }})</p></a></li>
			<li><p class="navbar-text">Signed in as <a href="{% url 'prose:profile' user.id %}">{{ user.username }}</a></p></li>

			{% else %}
			<li><a href="{% url 'prose:register' %}"><button type="button" class="btn btn-sm btn-primary">Register</button></a></li>
			<li><a href="{% url 'prose:login' %}"><button type="button" class="btn btn-sm btn-primary">Login</button></a></li>

			{% endif %}

		</ul>
	</div>

</nav>

<!-- Texture which hangs directly below the navbar -->
<div class="navbar-texture"></div>

pimpmyprose/templates/prose/pimp_list_item.html
<div class="pimpProseBox">
	<h3><a href="{% url 'prose:profile' pimp.user.id %}">{{ pimp.user.username }}</a></h3>

	<h4 id="pimp_{{ pimp.id }}_score">{{ pimp.score }}</h4>
	<h4>points</h4>
	<h4>{% include "prose/voting_interface.html" %}</h4>
	<h4>{{ pimp.percentMatch }}% match</h4>

	<p>{{ pimp.pimp_text }}</p>
	<h5>
		{% if show_parent_prose %}<a href="{% url 'prose:detail' pimp.prose_id %}">view parent Prose</a>{% endif %}
	</h5>
</div>

pimpmyprose/templates/prose/profile_manage.html
{% extends "prose/base.html" %}
{% block title %}Manage Profile - {{ user.username }}{% endblock %}

{% block content %}

<h1>Manage Profile: {{ user.username }}</h1>

{% if messages %}
<ul class="messages">
	{% for message in messages %}
	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	{% endfor %}
</ul>
{% endif %}

<form id="user_form" method="post" action="{% url 'prose:profile_manage' %}">
	{% csrf_token %}

	{{ userManage_form.as_p }}

	<button type="submit" class="btn btn-primary" name="submit" />Edit Profile</button>
</form>

{% endblock %}

pimpmyprose/templates/prose/voting_interface.html
{% if user.is_authenticated %}
<span data-pimp_id="{{ pimp.id }}" class="upvote voteArrow glyphicon glyphicon-triangle-top"></span>
<span data-pimp_id="{{ pimp.id }}" class="downvote voteArrow glyphicon glyphicon-triangle-bottom"></span>

{% endif %}