pimpmyprose/pimpmyprose/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Imports for Django Rest Framework
from rest_framework import routers
from prose import views

# Register routers for Prose and Pimp views
router = routers.DefaultRouter()
router.register( r'prose', views.ProseViewSet, base_name = 'prose' )
router.register( r'pimp', views.PimpViewSet, base_name = 'pimp' )

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pimpmyprose.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

	url( r'^', include( 'prose.urls', namespace = "prose" ) ),
    url( r'^admin/', include(admin.site.urls) ),

	# Urls for Django Rest Framework
	url( r'^api/', include( router.urls ) ),
	url( r'^api-auth/', include( 'rest_framework.urls', namespace = 'rest_framework' ) ),
)

# Include urls for static files. Offline deployment
# Only works of DEBUG is True
urlpatterns += staticfiles_urlpatterns()

pimpmyprose/prose/urls.py
from django.conf.urls import patterns, url, include

from prose import views


urlpatterns = patterns( '',
	# ex: /prose/
	url( r'^$', views.index, name = 'index' ),

	# angularJS version of detail
	# ex: /prose_angular/5/
	url( r'^(?P<prose_id>\d+)/$', views.detail, name = 'detail' ),

	# ex: /prose/pimp/10/upvote/
	url( r'^upvote/$', views.upvote, name = 'upvote' ),

	# ex: /prose/pimp/10/downvote/
	url( r'^downvote/$', views.downvote, name = 'downvote' ),

	# ex: /prose/register/
	url( r'^register/$', views.register, name = 'register' ),

	# ex: /prose/login/
	url( r'^login/$', views.user_login, name = 'login' ),

	# ex: /prose/logout/
	url( r'^logout/$', views.user_logout, name = 'logout' ),

	# ex: /prose/profile/1/
	url( r'^profile/(?P<user_id>\d+)/$', views.profile, name = 'profile' ),

	# ex: /prose/profile/manage/
	url( r'^profile/manage/$', views.profile_manage, name = 'profile_manage' ),

	# Users a certain user is following
	# ex: /prose/profile/1/following
	url( r'^profile/(?P<user_id>\d+)/following/$', views.following, name = 'following' ),

	# Pimps from all users a user is following
	# ex: /prose/profile/1/following/pimps
	url( r'^profile/(?P<user_id>\d+)/following/pimps/$', views.following_pimps, name = 'following_pimps' ),

	# Prose from all users a user is following
	# ex: /prose/profile/1/following/prose
	url( r'^profile/(?P<user_id>\d+)/following/prose/$', views.following_prose, name = 'following_prose' ),

	# Users who are following a certain user
	# ex: /prose/profile/1/followers
	url( r'^profile/(?P<user_id>\d+)/followers/$', views.followers, name = 'followers' ),

	# ex: /prose/notifications/
	url( r'^notifications/$', views.notifications, name = 'notifications' ),

	# ex: /prose/follow/
	url( r'^follow/$', views.followToggle, name = 'follow' ),

	# ex: /prose/search
	url( r'^search/$', include( 'haystack.urls' ) ),
)

pimpmyprose/templates/search/search.html
{% extends 'prose/base.html' %}

{% block title %}pimpMyProse - Search{% endblock %}

{% block content %}
<h2>Search</h2>

<form method="get" action=".">
	<table>
		{{ form.as_table }}
		<tr>
			<td>&nbsp;</td>
			<td>
				<input type="submit" value="Search">
			</td>
		</tr>
	</table>
	
	{% if query %}
	<h3>Results</h3>
	
		{% for result in page.object_list %}
		<p>
			<a href="{% url 'prose:detail' result.object.id %}">{{ result.object.prose_text }}</a>
		</p>
		{% empty %}
		<p>No results found.</p>
		{% endfor %}
		
		{% if page.has_previous or page.has_next %}
		<div>
		
		</div>
		{% endif %}
	{% else %}
		{# Show some example queries to run, maybe query syntax, something else? #}
	{% endif %}
	
</form>

{% endblock %}